language: node_js
node_js:
  - "stable"

env:
  global:
    - BUILD_TIMEOUT=10000


install:
  - npm install
script:
  - npm run build

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master